### PR TITLE
Fixing small issues

### LINKED ISSUE #48: Set seed in test including random number generators
Test-seasonal_onset includes generation of random numbers. Consider setting a seed so that it is reproduceable.

### LINKED ISSUE #49: Use start and end week numbers instead of season_weeks
In epi_calendar the arguments are 'start' and 'end' week numbers whereas in other places it is 'season_weeks' with c(start, end).

I suggest to introduce 'season_start' and 'season_end' instead. 'season_end' could have 'season_start - 1' as default.

### LINKED ISSUE #50: Consider how family argument comes from season* functions to fit_quantile
'fit_quantile()' has a family argument. When used in 'season_burden_levels()' the family argument is not explicit but through '...'. Consider making 'family' an explict argument in 'season_burden_levels()' and use it explicitly when calling 'fit_quantile'.

### PR DESCRIPTION
**Pull request by LasseEngboChr**
Fixes #48 
Fixes #49 
Fixes #50 

set.seed is added to relevant tests and addresses issue #48.

Changed season_weeks (Issue #49) to season_start and season_end.

The family argument is now explicit in seasonal_burden_onset (#50 ).

### Known issues
Lintr fails due to complexity - consider if this test is needed.

### Checklist

* [x] The PR passes all local unit tests
* [x] I have documented any new features introduced
* [x] If the PR adds a new feature, please add an entry in `NEWS.md`
* [x] A reviewer is assigned to this PR

### CODE REVIEW

**Review by SofiaOtero — APPROVED** [review]
Looks good, thanks for the improvements! 
I just removed the !! operator in `seasonal_burden_levels()` and added `# nolint: cyclocomp_linter.` for `seasonal_onset()`. we could consider adding [cyclocomp_linter](https://lintr.r-lib.org/reference/cyclocomp_linter.html) to the .lintr file. Now the default is 15 but we could increase it if we need it in more places.

**Review by RasmusSkytte — APPROVED** [review]

File: R/combined_seasonal_output.R [hunk 1]
```diff
@@ -87,21 +88,22 @@ combined_seasonal_output <- function(
...
 
   onset_output <- seasonal_onset(tsd = tsd, k = k, level = level, disease_threshold = disease_threshold,
                                  family = family, na_fraction_allowed = na_fraction_allowed,
-                                 season_weeks = season_weeks, only_current_season = only_current_season)
+                                 season_start = season_start, season_end = season_end,
+                                 only_current_season = only_current_season)
 
   # Extract seasons from onset_output and create seasonal_onset
   onset_output <- onset_output |>
     dplyr::group_by(.data$season) |>
```
Comment (SofiaOtero) [inline R/combined_seasonal_output.R:103]: I reset this to `dplyr::group_by(.data$season) |>`, when it was `dplyr::group_by("season") |>` it created an extra column "season" in the output data. I figured out it is need in `group_by()` because we are referencing a column (season) that exists in the data frame. On the other hand `select()` accepts strings or bare names.

**Comment by SofiaOtero** [comment]
This PR will fail now because I merged #53 to main recently.
